# Travis file for i2pd
# Documentation:
# - http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix
# - http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/
os:
  - linux
language:
  - cpp
compiler:
  - gcc
cache:
  - apt
branches:
  only:
    - master
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe" # Boost 1.50
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.50-all-dev libcrypto++9 libcrypto++-dev
script:
  - make
notifications:
  email:
    recipients:
      - meeh@sigterm.no
    on_success: change
    on_failure: always
  irc: 
    channels: 
      - "irc.freenode.net#i2p-dev"
    template:
      - "%{repository}/%{branch} [linux] (%{commit} - %{author}): %{message}"
    on_failure: always
    on_success: change

---

os:
  - osx
language:
  - cpp
compiler:
  - clang
branches:
  only:
    - master
install:
  - brew doctor;brew install boost cryptopp
script:
  - make -f Makefile.osx
notifications:
  email:
    recipients:
      - meeh@sigterm.no
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#i2p-dev"
    template:
      - "%{repository}/%{branch} [osx] (%{commit} - %{author}): %{message}"
    on_failure: always
    on_success: change

