# Travis file for i2pd
# Documentation:
# - http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix
# - http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/
language: cpp
compiler: gcc
os:
  - linux
  - osx
branches:
  only:
    - master
before_script:
  - if [[ "$os" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi # GCC 4.7
  - if [[ "$os" == "linux" ]]; then sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"; fi # Boost 1.50
  - if [[ "$os" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$os" == "linux" ]]; then sudo apt-get install -qq libboost1.50-all-dev libcrypto++9 libcrypto++-dev; fi
  - if [[ "$os" == "osx" ]]; then brew doctor;brew install boost cryptopp; fi
script:
  - if [[ "$os" == "osx" ]]; then make -f Makefile.osx; else; make; fi
notifications:
  email:
    recipients:
      - meeh@sigterm.no
    on_success: change
    on_failure: always
  irc: 
    channels: 
      - "irc.freenode.net#i2p-dev"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
    on_failure: always
    on_success: change


