language: cpp
matrix:
  allow_failures:
    - compiler: clang
compiler:
  - gcc
  - clang
cache:
  - apt
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe" # Boost 1.50
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.50-all-dev libcrypto++9 libcrypto++-dev
script:
  - make
notifications:
  email:
    recipients:
      - meeh@sigterm.no
    on_success: change
    on_failure: always
  irc: 
    channels: 
      - "irc.freenode.net#i2p-dev"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
    on_failure: always
    on_success: change


